// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_profile_service.proto

package user_profile_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// profile value支持的数据类型
type ProfileValueType int32

const (
	ProfileValueType_UNKNOW    ProfileValueType = 0
	ProfileValueType_STRING    ProfileValueType = 1
	ProfileValueType_INT       ProfileValueType = 2
	ProfileValueType_FLOAT     ProfileValueType = 3
	ProfileValueType_RAW_BYTES ProfileValueType = 4
	ProfileValueType_LIST      ProfileValueType = 5
)

var ProfileValueType_name = map[int32]string{
	0: "UNKNOW",
	1: "STRING",
	2: "INT",
	3: "FLOAT",
	4: "RAW_BYTES",
	5: "LIST",
}

var ProfileValueType_value = map[string]int32{
	"UNKNOW":    0,
	"STRING":    1,
	"INT":       2,
	"FLOAT":     3,
	"RAW_BYTES": 4,
	"LIST":      5,
}

func (x ProfileValueType) String() string {
	return proto.EnumName(ProfileValueType_name, int32(x))
}

func (ProfileValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{0}
}

// <name, version> 标识一个profile
type ProfileIdentity struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProfileIdentity) Reset()         { *m = ProfileIdentity{} }
func (m *ProfileIdentity) String() string { return proto.CompactTextString(m) }
func (*ProfileIdentity) ProtoMessage()    {}
func (*ProfileIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{0}
}

func (m *ProfileIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileIdentity.Unmarshal(m, b)
}
func (m *ProfileIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileIdentity.Marshal(b, m, deterministic)
}
func (m *ProfileIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileIdentity.Merge(m, src)
}
func (m *ProfileIdentity) XXX_Size() int {
	return xxx_messageInfo_ProfileIdentity.Size(m)
}
func (m *ProfileIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileIdentity proto.InternalMessageInfo

func (m *ProfileIdentity) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileIdentity) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type StringList struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringList) Reset()         { *m = StringList{} }
func (m *StringList) String() string { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()    {}
func (*StringList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{1}
}

func (m *StringList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringList.Unmarshal(m, b)
}
func (m *StringList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringList.Marshal(b, m, deterministic)
}
func (m *StringList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringList.Merge(m, src)
}
func (m *StringList) XXX_Size() int {
	return xxx_messageInfo_StringList.Size(m)
}
func (m *StringList) XXX_DiscardUnknown() {
	xxx_messageInfo_StringList.DiscardUnknown(m)
}

var xxx_messageInfo_StringList proto.InternalMessageInfo

func (m *StringList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

// type + 对应数据类型的value
type ProfileValue struct {
	Type ProfileValueType `protobuf:"varint,1,opt,name=type,proto3,enum=user_profile_pb.ProfileValueType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*ProfileValue_StrValue
	//	*ProfileValue_IntValue
	//	*ProfileValue_FloatValue
	//	*ProfileValue_BytesValue
	//	*ProfileValue_ListValue
	Value                isProfileValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProfileValue) Reset()         { *m = ProfileValue{} }
func (m *ProfileValue) String() string { return proto.CompactTextString(m) }
func (*ProfileValue) ProtoMessage()    {}
func (*ProfileValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{2}
}

func (m *ProfileValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileValue.Unmarshal(m, b)
}
func (m *ProfileValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileValue.Marshal(b, m, deterministic)
}
func (m *ProfileValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileValue.Merge(m, src)
}
func (m *ProfileValue) XXX_Size() int {
	return xxx_messageInfo_ProfileValue.Size(m)
}
func (m *ProfileValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileValue proto.InternalMessageInfo

func (m *ProfileValue) GetType() ProfileValueType {
	if m != nil {
		return m.Type
	}
	return ProfileValueType_UNKNOW
}

type isProfileValue_Value interface {
	isProfileValue_Value()
}

type ProfileValue_StrValue struct {
	StrValue string `protobuf:"bytes,2,opt,name=str_value,json=strValue,proto3,oneof"`
}

type ProfileValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ProfileValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type ProfileValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type ProfileValue_ListValue struct {
	ListValue *StringList `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof"`
}

func (*ProfileValue_StrValue) isProfileValue_Value() {}

func (*ProfileValue_IntValue) isProfileValue_Value() {}

func (*ProfileValue_FloatValue) isProfileValue_Value() {}

func (*ProfileValue_BytesValue) isProfileValue_Value() {}

func (*ProfileValue_ListValue) isProfileValue_Value() {}

func (m *ProfileValue) GetValue() isProfileValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ProfileValue) GetStrValue() string {
	if x, ok := m.GetValue().(*ProfileValue_StrValue); ok {
		return x.StrValue
	}
	return ""
}

func (m *ProfileValue) GetIntValue() int64 {
	if x, ok := m.GetValue().(*ProfileValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *ProfileValue) GetFloatValue() float64 {
	if x, ok := m.GetValue().(*ProfileValue_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (m *ProfileValue) GetBytesValue() []byte {
	if x, ok := m.GetValue().(*ProfileValue_BytesValue); ok {
		return x.BytesValue
	}
	return nil
}

func (m *ProfileValue) GetListValue() *StringList {
	if x, ok := m.GetValue().(*ProfileValue_ListValue); ok {
		return x.ListValue
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProfileValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProfileValue_StrValue)(nil),
		(*ProfileValue_IntValue)(nil),
		(*ProfileValue_FloatValue)(nil),
		(*ProfileValue_BytesValue)(nil),
		(*ProfileValue_ListValue)(nil),
	}
}

// 一个profile item: id + value
type ProfileItem struct {
	Id                   *ProfileIdentity `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                *ProfileValue    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ProfileItem) Reset()         { *m = ProfileItem{} }
func (m *ProfileItem) String() string { return proto.CompactTextString(m) }
func (*ProfileItem) ProtoMessage()    {}
func (*ProfileItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{3}
}

func (m *ProfileItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProfileItem.Unmarshal(m, b)
}
func (m *ProfileItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProfileItem.Marshal(b, m, deterministic)
}
func (m *ProfileItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileItem.Merge(m, src)
}
func (m *ProfileItem) XXX_Size() int {
	return xxx_messageInfo_ProfileItem.Size(m)
}
func (m *ProfileItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileItem.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileItem proto.InternalMessageInfo

func (m *ProfileItem) GetId() *ProfileIdentity {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ProfileItem) GetValue() *ProfileValue {
	if m != nil {
		return m.Value
	}
	return nil
}

// 用户及其对应的profile_list
type UserProfile struct {
	Uid                  uint64         `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	ProfileList          []*ProfileItem `protobuf:"bytes,2,rep,name=profile_list,json=profileList,proto3" json:"profile_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{4}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UserProfile) GetProfileList() []*ProfileItem {
	if m != nil {
		return m.ProfileList
	}
	return nil
}

type GetRequest struct {
	// 请求id，每个请求唯一
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 请求来源，方便追查
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// 用户id
	Uid uint64 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	// 要读取的profile列表
	ProfileList []*ProfileIdentity `protobuf:"bytes,4,rep,name=profile_list,json=profileList,proto3" json:"profile_list,omitempty"`
	// 实验的bucket
	Bucket string `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// options
	// 是否跳过cache
	DisableCache         bool     `protobuf:"varint,6,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *GetRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *GetRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GetRequest) GetProfileList() []*ProfileIdentity {
	if m != nil {
		return m.ProfileList
	}
	return nil
}

func (m *GetRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetRequest) GetDisableCache() bool {
	if m != nil {
		return m.DisableCache
	}
	return false
}

type GetResponse struct {
	// 状态码, =0正常, <0错误;
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	// 读取到的Profile数据
	ProfileList          []*ProfileItem `protobuf:"bytes,3,rep,name=profile_list,json=profileList,proto3" json:"profile_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{6}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *GetResponse) GetProfileList() []*ProfileItem {
	if m != nil {
		return m.ProfileList
	}
	return nil
}

type BatchGetRequest struct {
	// 请求id，每个请求唯一
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 请求来源，方便追查
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// 用户id列表
	Uids []uint64 `protobuf:"varint,3,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	// 要读取的profile列表
	ProfileList []*ProfileIdentity `protobuf:"bytes,4,rep,name=profile_list,json=profileList,proto3" json:"profile_list,omitempty"`
	// 实验的bucket
	Bucket string `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// options
	// 是否跳过cache
	DisableCache         bool     `protobuf:"varint,6,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchGetRequest) Reset()         { *m = BatchGetRequest{} }
func (m *BatchGetRequest) String() string { return proto.CompactTextString(m) }
func (*BatchGetRequest) ProtoMessage()    {}
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{7}
}

func (m *BatchGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetRequest.Unmarshal(m, b)
}
func (m *BatchGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetRequest.Marshal(b, m, deterministic)
}
func (m *BatchGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetRequest.Merge(m, src)
}
func (m *BatchGetRequest) XXX_Size() int {
	return xxx_messageInfo_BatchGetRequest.Size(m)
}
func (m *BatchGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetRequest proto.InternalMessageInfo

func (m *BatchGetRequest) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *BatchGetRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *BatchGetRequest) GetUids() []uint64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *BatchGetRequest) GetProfileList() []*ProfileIdentity {
	if m != nil {
		return m.ProfileList
	}
	return nil
}

func (m *BatchGetRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *BatchGetRequest) GetDisableCache() bool {
	if m != nil {
		return m.DisableCache
	}
	return false
}

type BatchGetResponse struct {
	// 状态码, =0正常, <0错误
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 错误信息
	ErrMsg string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	// 读取到的Profile数据
	Profiles             []*UserProfile `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BatchGetResponse) Reset()         { *m = BatchGetResponse{} }
func (m *BatchGetResponse) String() string { return proto.CompactTextString(m) }
func (*BatchGetResponse) ProtoMessage()    {}
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{8}
}

func (m *BatchGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetResponse.Unmarshal(m, b)
}
func (m *BatchGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetResponse.Marshal(b, m, deterministic)
}
func (m *BatchGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetResponse.Merge(m, src)
}
func (m *BatchGetResponse) XXX_Size() int {
	return xxx_messageInfo_BatchGetResponse.Size(m)
}
func (m *BatchGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetResponse proto.InternalMessageInfo

func (m *BatchGetResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BatchGetResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *BatchGetResponse) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

type SetRequest struct {
	// 请求id，每个请求唯一
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 请求来源，方便追查
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// 要写入的profile数据
	Profile *UserProfile `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	// options
	// 是否跳过cache
	DisableCache         bool     `protobuf:"varint,4,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{9}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *SetRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SetRequest) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

func (m *SetRequest) GetDisableCache() bool {
	if m != nil {
		return m.DisableCache
	}
	return false
}

type SetResponse struct {
	// 状态码, =0正常, <0错误
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 错误信息
	ErrMsg               string   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{10}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SetResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type BatchSetRequest struct {
	// 请求id，每个请求唯一
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 请求来源，方便追查
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// 要写入的profile数据
	Profiles []*UserProfile `protobuf:"bytes,3,rep,name=profiles,proto3" json:"profiles,omitempty"`
	// options
	// 是否跳过cache
	DisableCache         bool     `protobuf:"varint,4,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchSetRequest) Reset()         { *m = BatchSetRequest{} }
func (m *BatchSetRequest) String() string { return proto.CompactTextString(m) }
func (*BatchSetRequest) ProtoMessage()    {}
func (*BatchSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{11}
}

func (m *BatchSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchSetRequest.Unmarshal(m, b)
}
func (m *BatchSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchSetRequest.Marshal(b, m, deterministic)
}
func (m *BatchSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSetRequest.Merge(m, src)
}
func (m *BatchSetRequest) XXX_Size() int {
	return xxx_messageInfo_BatchSetRequest.Size(m)
}
func (m *BatchSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSetRequest proto.InternalMessageInfo

func (m *BatchSetRequest) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *BatchSetRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *BatchSetRequest) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func (m *BatchSetRequest) GetDisableCache() bool {
	if m != nil {
		return m.DisableCache
	}
	return false
}

type BatchSetResponse struct {
	// 状态码, =0正常, <0错误
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 错误信息
	ErrMsg               string   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchSetResponse) Reset()         { *m = BatchSetResponse{} }
func (m *BatchSetResponse) String() string { return proto.CompactTextString(m) }
func (*BatchSetResponse) ProtoMessage()    {}
func (*BatchSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{12}
}

func (m *BatchSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchSetResponse.Unmarshal(m, b)
}
func (m *BatchSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchSetResponse.Marshal(b, m, deterministic)
}
func (m *BatchSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchSetResponse.Merge(m, src)
}
func (m *BatchSetResponse) XXX_Size() int {
	return xxx_messageInfo_BatchSetResponse.Size(m)
}
func (m *BatchSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchSetResponse proto.InternalMessageInfo

func (m *BatchSetResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BatchSetResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type DeleteRequest struct {
	// 请求id，每个请求唯一
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 请求来源，方便追查
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// 用户id
	Uid uint64 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	// 要删除的profile列表
	ProfileList []*ProfileIdentity `protobuf:"bytes,4,rep,name=profile_list,json=profileList,proto3" json:"profile_list,omitempty"`
	// options
	// 是否跳过cache
	DisableCache         bool     `protobuf:"varint,5,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{13}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *DeleteRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *DeleteRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *DeleteRequest) GetProfileList() []*ProfileIdentity {
	if m != nil {
		return m.ProfileList
	}
	return nil
}

func (m *DeleteRequest) GetDisableCache() bool {
	if m != nil {
		return m.DisableCache
	}
	return false
}

type DeleteResponse struct {
	// 状态码, =0正常, <0错误;
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 错误信息
	ErrMsg               string   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{14}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DeleteResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type BatchDeleteRequest struct {
	// 请求id，每个请求唯一
	LogId int64 `protobuf:"varint,1,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// 请求来源，方便追查
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// 用户id列表
	Uids []uint64 `protobuf:"varint,3,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	// 要删除的profile列表
	ProfileList []*ProfileIdentity `protobuf:"bytes,4,rep,name=profile_list,json=profileList,proto3" json:"profile_list,omitempty"`
	// options
	// 是否跳过cache
	DisableCache         bool     `protobuf:"varint,5,opt,name=disable_cache,json=disableCache,proto3" json:"disable_cache,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchDeleteRequest) Reset()         { *m = BatchDeleteRequest{} }
func (m *BatchDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*BatchDeleteRequest) ProtoMessage()    {}
func (*BatchDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{15}
}

func (m *BatchDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDeleteRequest.Unmarshal(m, b)
}
func (m *BatchDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDeleteRequest.Marshal(b, m, deterministic)
}
func (m *BatchDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDeleteRequest.Merge(m, src)
}
func (m *BatchDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_BatchDeleteRequest.Size(m)
}
func (m *BatchDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDeleteRequest proto.InternalMessageInfo

func (m *BatchDeleteRequest) GetLogId() int64 {
	if m != nil {
		return m.LogId
	}
	return 0
}

func (m *BatchDeleteRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *BatchDeleteRequest) GetUids() []uint64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *BatchDeleteRequest) GetProfileList() []*ProfileIdentity {
	if m != nil {
		return m.ProfileList
	}
	return nil
}

func (m *BatchDeleteRequest) GetDisableCache() bool {
	if m != nil {
		return m.DisableCache
	}
	return false
}

type BatchDeleteResponse struct {
	// 状态码, =0正常, <0错误;
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// 错误信息
	ErrMsg               string   `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchDeleteResponse) Reset()         { *m = BatchDeleteResponse{} }
func (m *BatchDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*BatchDeleteResponse) ProtoMessage()    {}
func (*BatchDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee6e6d5e2b7b3a61, []int{16}
}

func (m *BatchDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchDeleteResponse.Unmarshal(m, b)
}
func (m *BatchDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchDeleteResponse.Marshal(b, m, deterministic)
}
func (m *BatchDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchDeleteResponse.Merge(m, src)
}
func (m *BatchDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_BatchDeleteResponse.Size(m)
}
func (m *BatchDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchDeleteResponse proto.InternalMessageInfo

func (m *BatchDeleteResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BatchDeleteResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterEnum("user_profile_pb.ProfileValueType", ProfileValueType_name, ProfileValueType_value)
	proto.RegisterType((*ProfileIdentity)(nil), "user_profile_pb.ProfileIdentity")
	proto.RegisterType((*StringList)(nil), "user_profile_pb.StringList")
	proto.RegisterType((*ProfileValue)(nil), "user_profile_pb.ProfileValue")
	proto.RegisterType((*ProfileItem)(nil), "user_profile_pb.ProfileItem")
	proto.RegisterType((*UserProfile)(nil), "user_profile_pb.UserProfile")
	proto.RegisterType((*GetRequest)(nil), "user_profile_pb.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "user_profile_pb.GetResponse")
	proto.RegisterType((*BatchGetRequest)(nil), "user_profile_pb.BatchGetRequest")
	proto.RegisterType((*BatchGetResponse)(nil), "user_profile_pb.BatchGetResponse")
	proto.RegisterType((*SetRequest)(nil), "user_profile_pb.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "user_profile_pb.SetResponse")
	proto.RegisterType((*BatchSetRequest)(nil), "user_profile_pb.BatchSetRequest")
	proto.RegisterType((*BatchSetResponse)(nil), "user_profile_pb.BatchSetResponse")
	proto.RegisterType((*DeleteRequest)(nil), "user_profile_pb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "user_profile_pb.DeleteResponse")
	proto.RegisterType((*BatchDeleteRequest)(nil), "user_profile_pb.BatchDeleteRequest")
	proto.RegisterType((*BatchDeleteResponse)(nil), "user_profile_pb.BatchDeleteResponse")
}

func init() { proto.RegisterFile("user_profile_service.proto", fileDescriptor_ee6e6d5e2b7b3a61) }

var fileDescriptor_ee6e6d5e2b7b3a61 = []byte{
	// 883 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x96, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0x3b, 0xb1, 0xf3, 0xe1, 0xe3, 0x64, 0x6b, 0x0d, 0x02, 0xa2, 0xd0, 0x82, 0xeb, 0xe5,
	0x22, 0xda, 0x8b, 0x16, 0xb2, 0x02, 0x21, 0x84, 0x58, 0xb5, 0x85, 0x6d, 0x23, 0x4a, 0x17, 0x8d,
	0xb3, 0x54, 0x5c, 0x20, 0xe3, 0x24, 0x53, 0xef, 0x08, 0xc7, 0x0e, 0x9e, 0x49, 0xa5, 0x5e, 0x20,
	0x24, 0x9e, 0x00, 0x09, 0xee, 0x78, 0x0f, 0xee, 0x78, 0x02, 0xee, 0xe0, 0x15, 0xb8, 0xe1, 0x2d,
	0xd0, 0x8c, 0xc7, 0xdb, 0xb4, 0xf9, 0xe8, 0xe2, 0x15, 0x52, 0xef, 0xc6, 0x73, 0xce, 0x9c, 0xff,
	0xf9, 0xff, 0xe6, 0xc8, 0x36, 0x74, 0x66, 0x9c, 0x66, 0xc1, 0x34, 0x4b, 0xcf, 0x59, 0x4c, 0x03,
	0x4e, 0xb3, 0x0b, 0x36, 0xa2, 0xbb, 0xd3, 0x2c, 0x15, 0x29, 0xde, 0xbc, 0x16, 0x9b, 0x0e, 0x3b,
	0x5b, 0x51, 0x9a, 0x46, 0x31, 0xdd, 0x0b, 0xa7, 0x6c, 0x2f, 0x4c, 0x92, 0x54, 0x84, 0x82, 0xa5,
	0x09, 0xcf, 0xd3, 0xbd, 0x47, 0xb0, 0xf9, 0x45, 0x9e, 0xdb, 0x1f, 0xd3, 0x44, 0x30, 0x71, 0x89,
	0x31, 0x98, 0x49, 0x38, 0xa1, 0x6d, 0xe4, 0xa2, 0xae, 0x45, 0xd4, 0x1a, 0xb7, 0xa1, 0x7e, 0x41,
	0x33, 0xce, 0xd2, 0xa4, 0x5d, 0x71, 0x51, 0xb7, 0x45, 0x8a, 0x47, 0xcf, 0x05, 0xf0, 0x45, 0xc6,
	0x92, 0xe8, 0x84, 0x71, 0x21, 0xcf, 0xc6, 0x8c, 0x8b, 0x36, 0x72, 0x0d, 0x79, 0x56, 0xae, 0xbd,
	0x9f, 0x2a, 0xd0, 0xd4, 0x1a, 0x5f, 0x86, 0xf1, 0x8c, 0xe2, 0xf7, 0xc0, 0x14, 0x97, 0xd3, 0x5c,
	0xe0, 0x5e, 0x6f, 0x67, 0xf7, 0x46, 0xc7, 0xbb, 0xf3, 0xc9, 0x83, 0xcb, 0x29, 0x25, 0x2a, 0x1d,
	0x6f, 0x83, 0xc5, 0x45, 0x16, 0x5c, 0xc8, 0x6d, 0xd5, 0x85, 0x75, 0xbc, 0x41, 0x1a, 0x5c, 0x64,
	0x79, 0xd5, 0x6d, 0xb0, 0x58, 0x22, 0x74, 0xd8, 0x70, 0x51, 0xd7, 0x90, 0x61, 0x96, 0x88, 0x3c,
	0xbc, 0x03, 0xf6, 0x79, 0x9c, 0x86, 0x45, 0x82, 0xe9, 0xa2, 0x2e, 0x3a, 0xde, 0x20, 0xa0, 0x36,
	0x9f, 0xa7, 0x0c, 0x2f, 0x05, 0xe5, 0x3a, 0xa5, 0xea, 0xa2, 0x6e, 0x53, 0xa6, 0xa8, 0xcd, 0x3c,
	0xe5, 0x23, 0x00, 0xe9, 0x49, 0x67, 0xd4, 0x5c, 0xd4, 0xb5, 0x7b, 0x6f, 0x2c, 0x18, 0xb8, 0x02,
	0x72, 0xbc, 0x41, 0x2c, 0x79, 0x40, 0x9d, 0x3e, 0xa8, 0x43, 0x55, 0x1d, 0xf4, 0x04, 0xd8, 0x05,
	0x75, 0x41, 0x27, 0xf8, 0x1d, 0xa8, 0xb0, 0xb1, 0xc2, 0x61, 0xf7, 0xdc, 0x55, 0x38, 0x8a, 0xfb,
	0x21, 0x15, 0x36, 0xc6, 0x0f, 0x75, 0x25, 0xc5, 0xc1, 0xee, 0x6d, 0xaf, 0x65, 0x48, 0xb4, 0xea,
	0x37, 0x60, 0x3f, 0xe5, 0x34, 0xd3, 0x21, 0xec, 0x80, 0x31, 0xd3, 0xb2, 0x26, 0x91, 0x4b, 0xfc,
	0x08, 0x9a, 0x45, 0x09, 0x75, 0x8b, 0x15, 0xd7, 0xe8, 0xda, 0xbd, 0xad, 0x95, 0x1d, 0x09, 0x3a,
	0x21, 0xb6, 0xde, 0x97, 0x6e, 0xbd, 0x3f, 0x10, 0xc0, 0x11, 0x15, 0x84, 0x7e, 0x37, 0xa3, 0x5c,
	0xe0, 0x57, 0xa1, 0x16, 0xa7, 0x51, 0xa0, 0x45, 0x0c, 0x52, 0x8d, 0xd3, 0xa8, 0x3f, 0x96, 0x43,
	0x72, 0x9e, 0xa5, 0x93, 0xfc, 0x0e, 0x89, 0x5a, 0x17, 0xcd, 0x18, 0x57, 0xcd, 0x1c, 0xde, 0x68,
	0xc6, 0x54, 0xcd, 0xdc, 0x8e, 0x67, 0xbe, 0x21, 0xfc, 0x1a, 0xd4, 0x86, 0xb3, 0xd1, 0xb7, 0x54,
	0xa8, 0xdb, 0xb4, 0x88, 0x7e, 0xc2, 0xf7, 0xa1, 0x35, 0x66, 0x3c, 0x1c, 0xc6, 0x34, 0x18, 0x85,
	0xa3, 0x67, 0xf9, 0x55, 0x36, 0x48, 0x53, 0x6f, 0x1e, 0xca, 0x3d, 0xef, 0x07, 0xb0, 0x95, 0x19,
	0x3e, 0x4d, 0x13, 0x4e, 0x65, 0x2d, 0x2e, 0x42, 0x31, 0xe3, 0xda, 0x8d, 0x7e, 0xc2, 0xaf, 0x43,
	0x9d, 0x66, 0x59, 0x30, 0xe1, 0x91, 0x76, 0x54, 0xa3, 0x59, 0xf6, 0x39, 0x8f, 0x16, 0x70, 0x1a,
	0xff, 0x15, 0xe7, 0x9f, 0x08, 0x36, 0x0f, 0x42, 0x31, 0x7a, 0x56, 0x8e, 0x29, 0x06, 0x73, 0xc6,
	0xc6, 0x5c, 0xe9, 0x9a, 0x44, 0xad, 0xef, 0x00, 0xd5, 0xef, 0xc1, 0xb9, 0xf2, 0x54, 0x16, 0xed,
	0x07, 0xd0, 0xd0, 0x0d, 0xf1, 0x95, 0x58, 0xe7, 0x66, 0x9d, 0x3c, 0xcf, 0xf6, 0x7e, 0x41, 0x00,
	0x7e, 0x29, 0x9c, 0xef, 0x43, 0x5d, 0x57, 0x51, 0x63, 0x7a, 0x9b, 0x64, 0x91, 0xbc, 0x48, 0xc5,
	0x5c, 0x42, 0xe5, 0x63, 0xb0, 0xfd, 0x97, 0x00, 0xe2, 0xfd, 0x5a, 0x8c, 0x4a, 0x39, 0x6f, 0xa5,
	0x79, 0xbe, 0x98, 0xbb, 0x43, 0x7d, 0xe7, 0x2f, 0x65, 0xf1, 0x37, 0x04, 0xad, 0x4f, 0x68, 0x4c,
	0x05, 0xbd, 0x3b, 0xef, 0x97, 0x05, 0xf7, 0xd5, 0x25, 0xee, 0xf7, 0xe1, 0x5e, 0xd1, 0x77, 0x59,
	0xef, 0xbf, 0x23, 0xc0, 0x8a, 0x60, 0x69, 0x00, 0xff, 0xdb, 0xcb, 0xe0, 0x85, 0x10, 0x3c, 0x86,
	0x57, 0xae, 0xb5, 0x5f, 0x92, 0xc3, 0x83, 0x33, 0x70, 0x6e, 0xfe, 0x1d, 0x60, 0x80, 0xda, 0xd3,
	0xd3, 0xcf, 0x4e, 0x9f, 0x9c, 0x39, 0x1b, 0x72, 0xed, 0x0f, 0x48, 0xff, 0xf4, 0xc8, 0x41, 0xb8,
	0x0e, 0x46, 0xff, 0x74, 0xe0, 0x54, 0xb0, 0x05, 0xd5, 0xc7, 0x27, 0x4f, 0xf6, 0x07, 0x8e, 0x81,
	0x5b, 0x60, 0x91, 0xfd, 0xb3, 0xe0, 0xe0, 0xab, 0xc1, 0xa7, 0xbe, 0x63, 0xe2, 0x06, 0x98, 0x27,
	0x7d, 0x7f, 0xe0, 0x54, 0x7b, 0xff, 0x98, 0x80, 0xe7, 0x06, 0xdc, 0xcf, 0xff, 0xa9, 0xf0, 0x00,
	0x8c, 0x23, 0x2a, 0xf0, 0xe2, 0x27, 0xfe, 0xea, 0x8d, 0xdc, 0xd9, 0x5a, 0x1e, 0xcc, 0x2d, 0x7a,
	0xf8, 0xc7, 0xbf, 0xfe, 0xfe, 0xb9, 0xd2, 0xf4, 0xea, 0x7b, 0x17, 0xef, 0xee, 0x45, 0x54, 0x7c,
	0x88, 0x1e, 0xc8, 0xaa, 0xfe, 0xd2, 0xaa, 0xfe, 0xba, 0xaa, 0xfe, 0xaa, 0xaa, 0x3c, 0xaf, 0xfa,
	0x35, 0xd4, 0x72, 0xbc, 0xf8, 0xcd, 0x85, 0xb3, 0xd7, 0xc6, 0xa6, 0xf3, 0xd6, 0xca, 0xf8, 0xb2,
	0xf2, 0x63, 0x1a, 0xcb, 0xf2, 0x0c, 0x1a, 0xc5, 0x7b, 0x1b, 0x2f, 0x8e, 0xc8, 0x8d, 0xcf, 0x54,
	0x67, 0x67, 0x4d, 0x86, 0x16, 0x69, 0x2b, 0x11, 0xec, 0xb5, 0xa4, 0xc8, 0x50, 0x46, 0x03, 0xcd,
	0xa7, 0x90, 0xf2, 0x57, 0x4b, 0xf9, 0xb7, 0x4a, 0xf9, 0xeb, 0xa5, 0x34, 0xb4, 0x0c, 0xec, 0xb9,
	0xc1, 0xc4, 0xf7, 0x97, 0xd7, 0xba, 0x8e, 0xef, 0xed, 0xf5, 0x49, 0xab, 0x35, 0x73, 0x92, 0xc3,
	0x9a, 0xfa, 0xf5, 0x7e, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x60, 0x32, 0xf3, 0xc7,
	0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserProfileServiceClient is the client API for UserProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserProfileServiceClient interface {
	// 线上读写接口
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// 批量读写接口，线上禁用, 仅用于线下集群
	BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error)
	BatchSet(ctx context.Context, in *BatchSetRequest, opts ...grpc.CallOption) (*BatchSetResponse, error)
	BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error)
}

type userProfileServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserProfileServiceClient(cc *grpc.ClientConn) UserProfileServiceClient {
	return &userProfileServiceClient{cc}
}

func (c *userProfileServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/user_profile_pb.UserProfileService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/user_profile_pb.UserProfileService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/user_profile_pb.UserProfileService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error) {
	out := new(BatchGetResponse)
	err := c.cc.Invoke(ctx, "/user_profile_pb.UserProfileService/BatchGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) BatchSet(ctx context.Context, in *BatchSetRequest, opts ...grpc.CallOption) (*BatchSetResponse, error) {
	out := new(BatchSetResponse)
	err := c.cc.Invoke(ctx, "/user_profile_pb.UserProfileService/BatchSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfileServiceClient) BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error) {
	out := new(BatchDeleteResponse)
	err := c.cc.Invoke(ctx, "/user_profile_pb.UserProfileService/BatchDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfileServiceServer is the server API for UserProfileService service.
type UserProfileServiceServer interface {
	// 线上读写接口
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// 批量读写接口，线上禁用, 仅用于线下集群
	BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error)
	BatchSet(context.Context, *BatchSetRequest) (*BatchSetResponse, error)
	BatchDelete(context.Context, *BatchDeleteRequest) (*BatchDeleteResponse, error)
}

// UnimplementedUserProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserProfileServiceServer struct {
}

func (*UnimplementedUserProfileServiceServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserProfileServiceServer) Set(ctx context.Context, req *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedUserProfileServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedUserProfileServiceServer) BatchGet(ctx context.Context, req *BatchGetRequest) (*BatchGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGet not implemented")
}
func (*UnimplementedUserProfileServiceServer) BatchSet(ctx context.Context, req *BatchSetRequest) (*BatchSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSet not implemented")
}
func (*UnimplementedUserProfileServiceServer) BatchDelete(ctx context.Context, req *BatchDeleteRequest) (*BatchDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDelete not implemented")
}

func RegisterUserProfileServiceServer(s *grpc.Server, srv UserProfileServiceServer) {
	s.RegisterService(&_UserProfileService_serviceDesc, srv)
}

func _UserProfileService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile_pb.UserProfileService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile_pb.UserProfileService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile_pb.UserProfileService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileService_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile_pb.UserProfileService/BatchGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).BatchGet(ctx, req.(*BatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileService_BatchSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).BatchSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile_pb.UserProfileService/BatchSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).BatchSet(ctx, req.(*BatchSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfileService_BatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfileServiceServer).BatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_profile_pb.UserProfileService/BatchDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfileServiceServer).BatchDelete(ctx, req.(*BatchDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user_profile_pb.UserProfileService",
	HandlerType: (*UserProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserProfileService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _UserProfileService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserProfileService_Delete_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _UserProfileService_BatchGet_Handler,
		},
		{
			MethodName: "BatchSet",
			Handler:    _UserProfileService_BatchSet_Handler,
		},
		{
			MethodName: "BatchDelete",
			Handler:    _UserProfileService_BatchDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_profile_service.proto",
}
